from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
import os
from datetime import date

router = APIRouter(prefix="/legal", tags=["Legal Tools"])

DEMO_MODE = os.getenv("DEMO_MODE", "false").lower() == "true"


class LegalRequest(BaseModel):
    tool: str  # second_appeal | consumer_complaint | legal_notice | labour_complaint
    # Second Appeal
    name: Optional[str] = None
    rti_date: Optional[str] = None
    appeal_date: Optional[str] = None
    department: Optional[str] = None
    query: Optional[str] = None
    reason: Optional[str] = None
    # Consumer
    address: Optional[str] = None
    company: Optional[str] = None
    type: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[str] = None
    purchase_date: Optional[str] = None
    relief: Optional[str] = None
    # Legal Notice
    sender: Optional[str] = None
    recipient: Optional[str] = None
    # Labour
    employer: Optional[str] = None
    state: Optional[str] = None
    # Shared
    details: Optional[str] = None


def generate_second_appeal_demo(req: LegalRequest) -> str:
    today = date.today().strftime("%d/%m/%Y")
    reason_map = {
        "no_response": "the First Appellate Authority failed to respond within the stipulated 30-day period",
        "incomplete": "the information provided was incomplete and did not address the specific queries raised",
        "denied": "the information was denied without citing any valid exemption under Section 8 of the RTI Act, 2005",
        "wrong_info": "the information provided was incorrect and misleading",
        "partial": "only partial information was furnished, and the remaining queries were not addressed",
        "delay": "the response was provided beyond the statutory 30-day deadline without valid justification",
    }
    reason_text = reason_map.get(req.reason or "no_response", reason_map["no_response"])

    return f"""Date: {today}

To,
The Registrar,
Central Information Commission,
August Kranti Bhawan, Bhikaji Cama Place,
New Delhi - 110066

Subject: Second Appeal under Section 19(3) of the Right to Information Act, 2005

Respected Sir/Madam,

The Appellant, {req.name or '[YOUR NAME]'}, hereby files this Second Appeal under Section 19(3) of the Right to Information Act, 2005 against the order/deemed refusal of the First Appellate Authority.

FACTS OF THE CASE:

1. The Appellant filed an RTI Application dated {req.rti_date or '[RTI DATE]'} before the Public Information Officer (PIO) of {req.department or '[DEPARTMENT NAME]'}, seeking the following information:

   "{req.query or '[YOUR RTI QUERY]'}"

2. The PIO responded / failed to respond within the stipulated 30-day period under Section 7(1) of the RTI Act, 2005.

3. The Appellant filed a First Appeal dated {req.appeal_date or '[FIRST APPEAL DATE]'} before the First Appellate Authority of {req.department or '[DEPARTMENT NAME]'} under Section 19(1) of the RTI Act, 2005.

4. The First Appeal outcome was unsatisfactory because {reason_text}.

{f"5. Additional Facts: {req.details}" if req.details else ""}

GROUNDS FOR SECOND APPEAL:

I. The refusal/non-response violates Section 7(1) of the RTI Act, 2005 which mandates a response within 30 days.

II. No valid exemption under Section 8 of the RTI Act, 2005 was cited to justify denial of information.

III. The Right to Information is a fundamental right under Article 19(1)(a) of the Constitution of India (as held by the Hon'ble Supreme Court in Union of India vs Namit Sharma).

IV. The information sought is a matter of public interest and does not fall under any exempted category.

RELIEF SOUGHT:

1. Direct the PIO/First Appellate Authority to provide the complete information as sought in the original RTI application.

2. Impose penalty on the PIO under Section 20(1) of the RTI Act, 2005 for non-compliance.

3. Award compensation to the Appellant for the loss and inconvenience caused.

DECLARATION:

I, {req.name or '[YOUR NAME]'}, hereby declare that the information given above is true and correct to the best of my knowledge and belief.

Yours sincerely,

{req.name or '[YOUR NAME]'}
Date: {today}

Enclosures:
1. Copy of original RTI Application
2. Copy of PIO's response (if any)
3. Copy of First Appeal
4. Copy of First Appellate Authority's response (if any)
5. Proof of postal dispatch (tracking receipt)

---
Generated by RTIAssist — Free Legal Tools for Indian Citizens
Note: File this within 90 days of receiving First Appeal response. No filing fee required."""


def generate_consumer_complaint_demo(req: LegalRequest) -> str:
    today = date.today().strftime("%d/%m/%Y")
    type_map = {
        "defective_product": "defective/sub-standard product",
        "service_deficiency": "deficiency in service",
        "refund_denied": "unfair trade practice (refund/return denied)",
        "misleading_ad": "misleading advertisement",
        "overcharging": "overcharging and unfair trade practice",
        "builder_delay": "deficiency in service (builder delay)",
        "insurance_claim": "deficiency in service (insurance claim rejection)",
        "bank_issue": "deficiency in banking/financial services",
        "medical_negligence": "medical negligence and deficiency in service",
    }
    type_text = type_map.get(req.type or "service_deficiency", "deficiency in service")
    relief_map = {
        "refund": "full refund of the amount paid",
        "replacement": "replacement of the defective product",
        "compensation": "compensation for the loss suffered",
        "service_completion": "completion of the agreed service",
        "all": "full refund, compensation for mental agony and inconvenience, and cost of litigation",
    }
    relief_text = relief_map.get(req.relief or "all", relief_map["all"])

    return f"""BEFORE THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION
[YOUR DISTRICT], [YOUR STATE]

Consumer Complaint No. ___/2026

IN THE MATTER OF:

{req.name or '[COMPLAINANT NAME]'}
{req.address or '[YOUR ADDRESS]'}
                                        ...COMPLAINANT

VERSUS

{req.company or '[COMPANY NAME]'}
[Registered Office Address]
                                        ...OPPOSITE PARTY

CONSUMER COMPLAINT UNDER SECTION 35 OF THE
CONSUMER PROTECTION ACT, 2019

To,
The Honourable President & Members,
District Consumer Disputes Redressal Commission,
[Your District]

MOST RESPECTFULLY SUBMITTED:

1. PARTIES:
   The Complainant, {req.name or '[YOUR NAME]'}, is a consumer as defined under Section 2(7) of the Consumer Protection Act, 2019.
   
   The Opposite Party, {req.company or '[COMPANY NAME]'}, is engaged in business/trade and falls within the ambit of Section 2(47) of the Act.

2. FACTS:
   {req.description or '[YOUR PROBLEM DESCRIPTION]'}
   
   Amount Involved: ₹{req.amount or '[AMOUNT]'}
   Date of Transaction: {req.purchase_date or '[DATE]'}

3. CAUSE OF ACTION:
   This complaint is filed for {type_text} against the Opposite Party.

4. LEGAL GROUND:
   Under Section 2(11) of the Consumer Protection Act, 2019, the act of the Opposite Party amounts to "deficiency in service" / "unfair trade practice."
   
   The Opposite Party has violated:
   - Consumer Protection Act, 2019 (Section 2(11) — Deficiency in Service)
   - Consumer Protection Act, 2019 (Section 2(47) — Unfair Trade Practice)

5. RELIEF SOUGHT:
   In view of the above facts, it is humbly prayed that this Hon'ble Commission may be pleased to:
   a) Direct the Opposite Party to provide {relief_text}
   b) Award compensation of ₹{int(req.amount or 0) // 2 if req.amount and req.amount.isdigit() else '50,000'}/- for mental agony, harassment, and inconvenience
   c) Award litigation costs of ₹5,000/-
   d) Any other relief deemed fit and proper

VERIFICATION:
I, {req.name or '[YOUR NAME]'}, the Complainant above named, do hereby verify that the contents of the above complaint are true and correct to the best of my knowledge and belief.

Date: {today}
Place: [YOUR CITY]

{req.name or '[YOUR NAME]'}
(Complainant)

Enclosures:
1. Invoice/Receipt
2. Correspondence with Opposite Party
3. Any warranty card / service agreement
4. Screenshots / evidence of the defect

---
Generated by RTIAssist Legal Tools — Free for all Indian Citizens
File online at: https://edaakhil.nic.in"""


def generate_legal_notice_demo(req: LegalRequest) -> str:
    today = date.today().strftime("%d/%m/%Y")
    type_sections = {
        "rent_deposit": "Section 106 of Transfer of Property Act, 1882 and Section 23 of Indian Contract Act, 1872",
        "property_dispute": "Section 5 of Specific Relief Act, 1963 and relevant provisions of Transfer of Property Act",
        "builder_delay": "RERA Act 2016 Section 18, Consumer Protection Act 2019",
        "money_recovery": "Order 37 CPC, Section 138 Negotiable Instruments Act (if cheque issued)",
        "cheque_bounce": "Section 138/139/141 of Negotiable Instruments Act, 1881",
        "employment": "Payment of Wages Act 1936, Industrial Disputes Act 1947, Section 25F and 25N",
        "defamation": "Section 499/500 IPC and Section 2(1)(c) of Defamation Act",
        "contract_breach": "Section 73 and 74 of Indian Contract Act, 1872",
        "family_maintenance": "Section 125 CrPC / Section 144 Bharatiya Nagarik Suraksha Sanhita",
    }
    section = type_sections.get(req.type or "contract_breach", "Indian Contract Act, 1872")

    return f"""LEGAL NOTICE

Date: {today}

To,
{req.recipient or '[RECIPIENT NAME]'}
[Recipient's Address]

Subject: Legal Notice under {section}

Sir/Madam,

Under instructions from and on behalf of my client, {req.sender or '[SENDER NAME]'}, I hereby give you the following LEGAL NOTICE:

1. BACKGROUND:
{req.description or '[ISSUE DESCRIPTION]'}

{f"2. AMOUNT IN DISPUTE: ₹{req.amount}/-" if req.amount else ""}

3. LEGAL POSITION:
Your acts/omissions as described above are illegal, unjust, and in violation of {section}. My client has suffered significant loss, inconvenience, and mental agony on account of your unlawful conduct.

4. DEMAND:
You are hereby called upon to:
a) Immediately comply with your legal obligations and remedy the grievance caused to my client
{f"b) Pay the sum of ₹{req.amount}/- due to my client within 15 days of receipt of this notice" if req.amount else "b) Comply with your legal obligations within 15 days of receipt of this notice"}
c) Provide written confirmation of compliance within the said period

5. CONSEQUENCE OF NON-COMPLIANCE:
Please note that if you fail to comply with the above demands within 15 (FIFTEEN) days from the date of receipt of this notice, my client will be constrained to initiate appropriate legal proceedings against you before the competent court/forum, including filing of civil/criminal complaints, at your risk, cost, and consequences.

This Notice is without prejudice to any other rights and remedies available to my client.

Yours faithfully,

{req.sender or '[SENDER NAME]'}
Address: [YOUR FULL ADDRESS]
Date: {today}

Note: Send via Registered Post with Acknowledgement Due (RPAD)
---
Generated by RTIAssist Legal Tools — Free for all Indian Citizens"""


def generate_labour_complaint_demo(req: LegalRequest) -> str:
    today = date.today().strftime("%d/%m/%Y")
    act_map = {
        "salary_unpaid": "Section 15 of Payment of Wages Act, 1936",
        "wrongful_termination": "Section 25F of Industrial Disputes Act, 1947",
        "pf_not_deposited": "Section 14A/14B of Employees' Provident Funds and Miscellaneous Provisions Act, 1952",
        "esi_not_provided": "Section 85 of Employees' State Insurance Act, 1948",
        "overtime_unpaid": "Section 59 of Factories Act, 1948",
        "forced_resignation": "Section 2(oo) of Industrial Disputes Act (deemed retrenchment)",
        "gratuity_denied": "Section 4 of Payment of Gratuity Act, 1972",
        "contract_violation": "Section 73 of Indian Contract Act, 1872",
        "work_conditions": "Sections 11-20 of Factories Act, 1948",
    }
    act = act_map.get(req.type or "salary_unpaid", "Industrial Disputes Act, 1947")

    return f"""Date: {today}

To,
The Labour Commissioner,
Office of the Labour Commissioner,
{req.state or '[YOUR STATE]'} Government,
[District Office Address]

Subject: Formal Complaint against {req.employer or '[EMPLOYER NAME]'} — Violation of {act}

Respected Sir/Madam,

I, {req.name or '[YOUR NAME]'}, am filing this formal complaint against my employer, {req.employer or '[EMPLOYER NAME]'}, for the following:

DETAILS OF EMPLOYMENT:
- Employee Name: {req.name or '[YOUR NAME]'}
- Employer/Company: {req.employer or '[EMPLOYER NAME]'}
- Nature of Employment: [Designation/Role]
- Period of Employment: [Joining Date] to [Last Working Date / Present]

NATURE OF COMPLAINT:
{req.description or '[DETAILED DESCRIPTION OF THE PROBLEM]'}

{f"Amount Owed: ₹{req.amount}/-" if req.amount else ""}

LEGAL VIOLATIONS:
The conduct of the employer is in violation of:
1. {act}
2. [Applicable State Labour Laws]
3. Any relevant provisions of the Minimum Wages Act, 1948

RELIEF SOUGHT:
1. Immediate inquiry into the above complaint
{f"2. Direction to the employer to pay ₹{req.amount}/- along with applicable interest" if req.amount else "2. Direction to the employer to comply with applicable labour laws"}
3. Appropriate penalty action against the employer under relevant laws
4. Any other relief deemed fit by this office

DECLARATION:
I hereby declare that the information provided above is true and correct to the best of my knowledge and belief.

Yours faithfully,

{req.name or '[YOUR NAME]'}
Address: [YOUR FULL ADDRESS]
Mobile: [YOUR PHONE]
Date: {today}

Enclosures:
1. Copy of Appointment Letter / Offer Letter
2. Salary Slips (if available)
3. Bank Statements showing salary credits/non-credits
4. Any written communication with employer
5. Employee ID / Joining Letter

---
Generated by RTIAssist Legal Tools — Free for all Indian Citizens
For PF complaints, also visit: https://epfindia.gov.in"""


@router.post("/generate")
async def generate_legal_document(req: LegalRequest):
    """Generate legal documents — Second Appeal, Consumer Complaint, Legal Notice, Labour Complaint"""

    if not req.tool:
        raise HTTPException(status_code=400, detail="Tool type is required")

    # Use demo mode for all tools (can be replaced with AI API calls later)
    if req.tool == "second_appeal":
        if not req.query or not req.department:
            raise HTTPException(status_code=400, detail="Department and RTI query are required")
        draft = generate_second_appeal_demo(req)

    elif req.tool == "consumer_complaint":
        if not req.company or not req.description:
            raise HTTPException(status_code=400, detail="Company name and description are required")
        draft = generate_consumer_complaint_demo(req)

    elif req.tool == "legal_notice":
        if not req.sender or not req.recipient or not req.description:
            raise HTTPException(status_code=400, detail="Sender, recipient, and description are required")
        draft = generate_legal_notice_demo(req)

    elif req.tool == "labour_complaint":
        if not req.employer or not req.description:
            raise HTTPException(status_code=400, detail="Employer name and description are required")
        draft = generate_labour_complaint_demo(req)

    else:
        raise HTTPException(status_code=400, detail=f"Unknown tool: {req.tool}")

    return {"draft": draft, "tool": req.tool, "status": "success"}
