"""phase_17_source_registry

Revision ID: 1e36fdfea038
Revises: 6f374f18fcab
Create Date: 2026-09-03 12:24:50.478718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e36fdfea038'
down_revision: Union[str, Sequence[str], None] = '6f374f18fcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_authority_sources',
    sa.Column('authority_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_fetch_status', sa.String(), nullable=True),
    sa.Column('last_fetch_error', sa.String(), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_parse_status', sa.String(), nullable=True),
    sa.Column('last_content_hash', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_authority_sources_authority_id'), 'official_authority_sources', ['authority_id'], unique=False)
    op.create_index(op.f('ix_official_authority_sources_review_status'), 'official_authority_sources', ['review_status'], unique=False)
    op.create_index(op.f('ix_official_authority_sources_source_url'), 'official_authority_sources', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_official_authority_sources_source_url'), table_name='official_authority_sources')
    op.drop_index(op.f('ix_official_authority_sources_review_status'), table_name='official_authority_sources')
    op.drop_index(op.f('ix_official_authority_sources_authority_id'), table_name='official_authority_sources')
    op.drop_table('official_authority_sources')
    # ### end Alembic commands ###
