"""phase_19_source_monitoring_fields

Revision ID: 3f7827838980
Revises: bfea32a0fa55
Create Date: 2026-09-03 23:55:17.098029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7827838980'
down_revision: Union[str, Sequence[str], None] = 'bfea32a0fa55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_authority_sources', sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('official_authority_sources', sa.Column('consecutive_failures', sa.Integer(), nullable=True))
    op.add_column('official_authority_sources', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('official_authority_sources', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    
    op.create_index(op.f('ix_official_authority_sources_next_check_at'), 'official_authority_sources', ['next_check_at'], unique=False)
    op.create_index(op.f('ix_official_authority_sources_is_locked'), 'official_authority_sources', ['is_locked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_official_authority_sources_is_locked'), table_name='official_authority_sources')
    op.drop_index(op.f('ix_official_authority_sources_next_check_at'), table_name='official_authority_sources')
    
    op.drop_column('official_authority_sources', 'locked_at')
    op.drop_column('official_authority_sources', 'is_locked')
    op.drop_column('official_authority_sources', 'consecutive_failures')
    op.drop_column('official_authority_sources', 'next_check_at')
    # ### end Alembic commands ###
