"""Phase 13 case intelligence

Revision ID: 6f374f18fcab
Revises: 6f381f629831
Create Date: 2026-08-26 10:10:15.081667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f374f18fcab'
down_revision: Union[str, Sequence[str], None] = '6f381f629831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_objective', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('extracted_facts', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('facts_confirmed', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('next_action_recommendation', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('generation_context', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('generated_from_case_version', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('quality_check_result', sa.JSON(), nullable=True))
    op.add_column('response_analyses', sa.Column('request_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_analyses', 'request_mapping')
    op.drop_column('documents', 'quality_check_result')
    op.drop_column('documents', 'generated_from_case_version')
    op.drop_column('documents', 'generation_context')
    op.drop_column('cases', 'next_action_recommendation')
    op.drop_column('cases', 'facts_confirmed')
    op.drop_column('cases', 'extracted_facts')
    op.drop_column('cases', 'case_objective')
    # ### end Alembic commands ###
